In [2]:
#Numpy: It is a library for the Python programming language, adding support for large, multi-dimensional arrays and 
# matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
#It is the fundamental package for scientific computing with Python.
import numpy as np



In [6]:
# Create a numpy array
# Numpy arrays are a grid of values, all of the same type, and are indexed by a tuple of non-negative integers.
# The number of dimensions is the rank of the array, and the shape of an array is a
# tuple of integers giving the size of the array in each dimension.
## Here we create a 1D numpy array with integers from 1 to 5. 
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.shape)  # Output: (5,)
print(type(arr1))  # Output: <class 'numpy.ndarray'>
print(arr1.dtype)  # Output: int64 (or int32 depending on the platform)
# Create a 2D numpy array
# Here we create a 2D numpy array with integers from 1 to 6.
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)  # Output: (2, 3) - 2 rows and 3 columns
print(type(arr2))  # Output: <class 'numpy.ndarray'>

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
int64
[[1 2 3]
 [4 5 6]]
(2, 3)
<class 'numpy.ndarray'>


In [5]:
arr2.shape

(2, 3)

In [ ]:
arr_str = np.array(['apple', 'banana', 'cherry'])
print(arr_str)
print(arr_str.dtype)
# In NumPy, the dtype for string arrays is not shown as "string" but as something like 
# <U6 or |S6:

# <U6 means Unicode string with up to 6 characters.
# |S6 means byte string with up to 6 bytes.

['apple' 'banana' 'cherry']
<U6


In [9]:
arr3=np.array([["Ab","Cd","Ef"],["Gh","Ij","Kl"] ])
print(arr3)
print(arr3.shape)  # Output: (2, 3) - 2 rows and 3 columns
print(type(arr3))  # Output: <class 'numpy.ndarray'>
print(arr3.dtype)  # Output: <U2 - Unicode string of length 2

[['Ab' 'Cd' 'Ef']
 ['Gh' 'Ij' 'Kl']]
(2, 3)
<class 'numpy.ndarray'>
<U2


In [10]:
arr4=np.array([True,False])
print(arr4)
print(arr4.dtype)  # Output: bool - Boolean type

[ True False]
bool


In [11]:
#reshaping an array
# Reshaping an array means changing its shape without changing its data.
arr5 = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr5 = arr5.reshape((2, 3))  # Reshape to 2 rows and 3 columns
print(reshaped_arr5)    # Output: [[1 2 3]
                        #          [4 5 6]]     
print(reshaped_arr5.shape)  # Output: (2, 3)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
#numpy array with random values
# You can create a numpy array with random values using np.random.  
# random.rand() function.
random_arr = np.random.rand(3, 2)  # Create a 3x2 array with random values
print(random_arr)       
print(random_arr.shape)  # Output: (3, 2) - 3 rows and 2 columns